### GET request to example server
POST http://localhost:7000/patient/create
Content-Type: application/json

{
  "name": "mareenraj",
  "email": "",
  "address": "st, peters road, Navaly south, Manipay, Jaffna.",
  "dateOfBirth": "1999-08-07",
  "registeredDate": "2099-08-07"
}

###